name: Validate Codebase Workflow

on:
  workflow_call:

jobs:
  lint:
    name: Lint Check
    runs-on: ubuntu-latest
    steps:
      - uses: ./.github/actions/setup-node-deps
      - name: Run linter
        run: npm run lint

  typecheck:
    name: TypeScript Check
    runs-on: ubuntu-latest
    steps:
      - uses: ./.github/actions/setup-node-deps
      - name: Run TypeScript type checks
        run: npx tsc --noEmit

  tests:
    name: Test Suite
    runs-on: ubuntu-latest
    steps:
      - uses: ./.github/actions/setup-node-deps
      - name: Run tests
        run: npm test
